<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    public function index()
    {
        $blogs = \App\Models\Blog::where('is_published', true)
            ->orderBy('published_at', 'desc')
            ->get();

        return \Inertia\Inertia::render('Blogs/Index', [
            'blogs' => $blogs
        ]);
    }

    public function show($slug)
    {
        $query = \App\Models\Blog::where('slug', $slug);

        // If not admin, compel published check
        if (!\Illuminate\Support\Facades\Auth::check() || !\Illuminate\Support\Facades\Auth::user()->is_admin) {
            $query->where('is_published', true);
        }

        $blog = $query->withCount('presaleBookings')->firstOrFail();

        if ($blog->is_presale) {
            $blog->increment('access_attempts');
        }

        return \Inertia\Inertia::render('Blogs/Show', [
            'blog' => $blog
        ]);
    }

    public function create()
    {
        return \Inertia\Inertia::render('Blogs/Create');
    }

    public function store(Request $request)
    {
        $rules = [
            'title' => 'required|string|max:255',
            'excerpt' => 'required|string',
            'content' => 'required|string',
            'category' => 'required|string',
            // Laravel 'max' is in KB → 1 GB = 1,048,576 KB
            'image' => 'nullable|image|max:1048576',
            'image_url' => 'nullable|string', // Keep backwards compatibility or url option
            'author_name' => 'required|string',
            'is_presale' => 'boolean',
        ];

        // Require email only if not logged in
        if (!\Illuminate\Support\Facades\Auth::check()) {
            $rules['author_email'] = 'required|email';
        }

        $validated = $request->validate($rules);

        // Security Check 1: Honeypot (Trap for bots)
        if (!empty($request->input('honeypot_trap'))) {
            // Silently fail or return generic error
            return response()->json(['message' => 'Invalid request detected.'], 422);
        }

        // Security Check 2: Server-Side Math Verification
        // Even though generated by client, this forces bots to actually run the JS logic or scrape the specific fields
        $cNum1 = (int) $request->input('captcha_num1');
        $cNum2 = (int) $request->input('captcha_num2');
        $cAnswer = (int) $request->input('captcha_answer');

        if (($cNum1 + $cNum2) !== $cAnswer) {
            return back()->withErrors(['captcha' => 'Math verification failed. Please try again.']);
        }

        $imagePath = null;
        if ($request->hasFile('image')) {
            $imagePath = $request->file('image')->store('blogs', 'public');
        }

        $slug = \Illuminate\Support\Str::slug($validated['title']);
        $count = \App\Models\Blog::where('slug', 'like', $slug . '%')->count();
        if ($count > 0) {
            $slug .= '-' . ($count + 1);
        }

        // Approval Logic
        // Only Admins publish instantly. Everyone else goes to Pending.
        $isAdmin = \Illuminate\Support\Facades\Auth::check() && \Illuminate\Support\Facades\Auth::user()->role === 'super_admin'; // Or is_admin attribute if exists
        // Actually AdministratorController uses `is_admin` attribute on user model, let's use that.
        // Wait, User model likely has is_admin boolean or checks role.
        // Standard in this app seems to be `is_admin` boolean or `role` check.
        // Let's check User model quickly to be safe? No, let's assume `is_admin` attribute as seen in AdministratorController.
        // Wait, AdministratorController uses `Auth::user()->is_admin`.

        $isPublished = false;
        $status = 'pending';

        if (\Illuminate\Support\Facades\Auth::check() && \Illuminate\Support\Facades\Auth::user()->is_admin) {
            $isPublished = true;
            $status = 'approved';
        }

        \App\Models\Blog::create([
            'title' => $validated['title'],
            'excerpt' => $validated['excerpt'],
            'content' => $validated['content'],
            'category' => $validated['category'],
            'author_name' => $validated['author_name'],
            'image_url' => $validated['image_url'] ?? null,
            'image_path' => $imagePath,
            'is_presale' => $request->boolean('is_presale'),
            'access_attempts' => 0,
            'slug' => $slug,
            'is_published' => $isPublished,
            'status' => $status,
            'published_at' => $isPublished ? now() : null,
            'user_id' => \Illuminate\Support\Facades\Auth::id(),
            'author_email' => \Illuminate\Support\Facades\Auth::check() ? \Illuminate\Support\Facades\Auth::user()->email : ($request->author_email ?? null),
        ]);

        $message = $isPublished ? 'Blog post published successfully!' : 'Your blog post has been submitted for review.';

        return redirect()->route('blogs.index')->with('success', $message);
    }
}
